/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from ERROR: getGeneratedExterns called without rootDir:
/** @const */
var angular_material$src$youtube$2dplayer$youtube$2dplayer = {};
/** @type {?} */
Window.prototype.YT;
/** @type {?} */
Window.prototype.onYouTubeIframeAPIReady;
